# Generated by Django 4.2.3 on 2023-11-29 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
